MySQL:
  host: localhost
  port: 3306
  user: root
  database: minecraft
  password: ''


Discord:
  token: CLIENTTOKEN
  game: Minecraft

Roles:
## If you are using BungeeCord you must give the user the permission "group.<groupname>"
## To get role ids just write  ad dm with "!roles" to your bot
  defaultrole: 7
  group:
    admin: 1
    moderator: 2
    premium: 1
Messages:
  verify: '&7[&aDiscord&7]&r Please send this message to our bot "!verify %code%"'
  running: '&7[&aDiscord&7]&c There is already a verfication request in our system for you your code was %code%'
  verified: '&7[&aDiscord&7]&c You are already verified use /discord unlink to unlink your account'
  notverified: '&7[&aDiscord&7]&c You are not verified use /discord verify to verify your account'
  unlinked: '&7[&aDiscord&7]&c Successfully unlinked'
  ts3join: 'Hey %user%, you are not verified yet if you want to be use /discord verify ingame'
  invalidcode: 'Your code was invalid!'
  success: 'Successfully linked with **%discord%**'
  updated: '&7[&aDiscord&7]&c Successfully updated discord ranks'
  help: 'Commands: %nl /discord verify %nl /discord unlink %nl /discord update'

